// <auto-generated />
namespace SCORM1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correctAnswersQuantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctAnswersQuantity));
        
        string IMigrationMetadata.Id
        {
            get { return "202011122141394_correctAnswersQuantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
